sudo: false

language: node_js
node_js:
  - "19"
  - "18"

addons:
  apt:
    packages:
    - make
    #- wine

# need spectron test
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"

script:
  - make ci-test

